-- AlterEnum
ALTER TYPE "Source" ADD VALUE 'WORKINGNOMADS';
ALTER TYPE "Source" ADD VALUE 'LANDINGJOBS';
ALTER TYPE "Source" ADD VALUE 'THEMUSE';
ALTER TYPE "Source" ADD VALUE 'JOBSPRESSO';
ALTER TYPE "Source" ADD VALUE 'WORKABLE';
ALTER TYPE "Source" ADD VALUE 'SMARTRECRUITERS';
